[package]
name = "pyre"
version = "0.1.0"
edition = "2021"
description = "The better pypi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
dialoguer = "0.10.0"
toml = "0.5.8"